apiVersion: v1
kind: Secret
metadata:
  name: ticketing-secrets
  labels:
    app: ticketing-platform
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: rootpassword
  VNPAY_TMN_CODE: YOUR_VNP_TMN_CODE
  VNPAY_HASH_SECRET: YOUR_VNP_HASH_SECRET
  SMTP_USERNAME: your-email@example.com
  SMTP_PASSWORD: your-email-password

