apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ticket-system/user-service:dev
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: ticketing-config
            - secretRef:
                name: ticketing-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://$(MYSQL_HOST):3306/userdb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: MYSQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: MYSQL_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: ticketing-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ticketing-config
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: ticketing-config
                  key: REDIS_PORT
            - name: SPRING_CLOUD_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: ticketing-config
                  key: CONSUL_HOST
            - name: SPRING_CLOUD_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: ticketing-config
                  key: CONSUL_PORT
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://$(ELASTICSEARCH_HOST):$(ELASTICSEARCH_PORT)
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: ticketing-config
                  key: KEYCLOAK_JWK_SET_URI
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 20

